services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-web
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
